spring:
  datasource:
    url: jdbc:mysql://localhost:3307/banking_core_service
    username: root
    password: strong_password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8092

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka

#info:
#  app:
#    name: ${spring.application.name}


##ACTUATOR ENDPOINT CONFIGURATIONS
management:
  endpoints:
    web:
      exposure:
        include: info,health,configprops
  info:
    env:
      enabled: true
#
#logging:
#  file:
#    name: '/var/log/core-banking-service/application.log'